/**
 * Every sound that ships with the app.
 *
 * GENERATED by tools/sounds.mjs from static/audio/manifest.json — do not edit.
 * Adding a track is an edit to that manifest and a run of the script; nothing
 * here is a decision anybody should be making by hand.
 */

export type SoundRole =
    /** Plays under a whole scene, looping and cross-fading into the next. */
    | "bed"
    /** A short musical sting, fired on a beat. */
    | "cue"
    /** A one-off effect. */
    | "sfx";

export interface Sound {
    id: string;
    role: SoundRole;
    /** Served from static/, so this is the URL as the page sees it. */
    file: string;
    seconds: number;
    mood: string[];
    description: string;
    /** Alternate takes of the same prompt share a take name. */
    take?: string;
}

export const SOUNDS: Sound[] = [
    { id: "fairy-tale-ambience", role: "bed", file: "/audio/music/fairy-tale-ambience.opus", seconds: 120, mood: ["happy","gentle","storybook"], description: "Happy fairy tale ambience, sits well under narration." },
    { id: "fantasy-forest-1", role: "bed", file: "/audio/music/fantasy-forest-1.opus", seconds: 120, mood: ["whimsical","mysterious","airy"], description: "Orchestral fantasy: gentle harp, plucked strings, soft woodwinds, forest ambiance, airy reverb.", take: "fantasy-forest" },
    { id: "fantasy-forest-2", role: "bed", file: "/audio/music/fantasy-forest-2.opus", seconds: 120, mood: ["whimsical","mysterious","airy"], description: "Orchestral fantasy: gentle harp, plucked strings, soft woodwinds, forest ambiance, airy reverb.", take: "fantasy-forest" },
    { id: "mystery-underscore-1", role: "bed", file: "/audio/music/mystery-underscore-1.opus", seconds: 120, mood: ["tense","mysterious","playful"], description: "Orchestral theater underscore: staccato strings, plucked harp, light woodwinds, timpani rolls, dry close mix.", take: "mystery-underscore" },
    { id: "mystery-underscore-2", role: "bed", file: "/audio/music/mystery-underscore-2.opus", seconds: 120, mood: ["tense","mysterious","playful"], description: "Orchestral theater underscore: staccato strings, plucked harp, light woodwinds, timpani rolls, dry close mix.", take: "mystery-underscore" },
    { id: "superhero-triumph-1", role: "bed", file: "/audio/music/superhero-triumph-1.opus", seconds: 120, mood: ["epic","triumphant","dramatic"], description: "Epic superhero: soaring brass, heroic strings, bold timpani, choir swells, wide concert hall.", take: "superhero-triumph" },
    { id: "superhero-triumph-2", role: "bed", file: "/audio/music/superhero-triumph-2.opus", seconds: 120, mood: ["epic","triumphant","dramatic"], description: "Epic superhero: soaring brass, heroic strings, bold timpani, choir swells, wide concert hall.", take: "superhero-triumph" },
    { id: "superhero-triumph-3", role: "bed", file: "/audio/music/superhero-triumph-3.opus", seconds: 120, mood: ["epic","triumphant","dramatic"], description: "Epic superhero: soaring brass, heroic strings, bold timpani, choir swells, wide concert hall.", take: "superhero-triumph" },
    { id: "anticipation-hushed-1", role: "cue", file: "/audio/cues/anticipation-hushed-1.opus", seconds: 4, mood: ["anticipatory","hushed","tense"], description: "Theatrical underscore: creaking piano, lone cello, tense pizzicato, sparse timpani. Holds a beat before something happens.", take: "anticipation-hushed" },
    { id: "anticipation-hushed-2", role: "cue", file: "/audio/cues/anticipation-hushed-2.opus", seconds: 4, mood: ["anticipatory","hushed","tense"], description: "Theatrical underscore: creaking piano, lone cello, tense pizzicato, sparse timpani. Holds a beat before something happens.", take: "anticipation-hushed" },
    { id: "anticipation-hushed-3", role: "cue", file: "/audio/cues/anticipation-hushed-3.opus", seconds: 4, mood: ["anticipatory","hushed","tense"], description: "Theatrical underscore: creaking piano, lone cello, tense pizzicato, sparse timpani. Holds a beat before something happens.", take: "anticipation-hushed" },
    { id: "danger-glockenspiel", role: "cue", file: "/audio/cues/danger-glockenspiel.opus", seconds: 3, mood: ["dangerous","playful","warning"], description: "Staccato acoustic guitar, woodwind trills, fingerpicked banjo with dangerous glockenspiel accents. Trouble, lightly. Pairs with `scared`." },
    { id: "disappointed-banjo-1", role: "cue", file: "/audio/cues/disappointed-banjo-1.opus", seconds: 3, mood: ["disappointed","deflating","folksy"], description: "Folk miniature that sags: guitar, woodwind trills, fingerpicked banjo. Pairs with `cry` or a failed attempt.", take: "disappointed-banjo" },
    { id: "disappointed-banjo-2", role: "cue", file: "/audio/cues/disappointed-banjo-2.opus", seconds: 3, mood: ["disappointed","deflating","folksy"], description: "Folk miniature that sags: guitar, woodwind trills, fingerpicked banjo. Pairs with `cry` or a failed attempt.", take: "disappointed-banjo" },
    { id: "disappointed-banjo-3", role: "cue", file: "/audio/cues/disappointed-banjo-3.opus", seconds: 3, mood: ["disappointed","deflating","folksy"], description: "Folk miniature that sags: guitar, woodwind trills, fingerpicked banjo. Pairs with `cry` or a failed attempt.", take: "disappointed-banjo" },
    { id: "light-and-airy-1", role: "cue", file: "/audio/cues/light-and-airy-1.opus", seconds: 5, mood: ["light","airy","delicate"], description: "Fluttering woodwinds, harp glissando, soft pizzicato, shimmering chimes. A gentle arrival or reveal.", take: "light-and-airy" },
    { id: "light-and-airy-2", role: "cue", file: "/audio/cues/light-and-airy-2.opus", seconds: 5, mood: ["light","airy","delicate"], description: "Fluttering woodwinds, harp glissando, soft pizzicato, shimmering chimes. A gentle arrival or reveal.", take: "light-and-airy" },
    { id: "surprise-staccato-1", role: "cue", file: "/audio/cues/surprise-staccato-1.opus", seconds: 3, mood: ["surprised","playful","sparse"], description: "Folk miniature, playful staccato, dry room tone. A barer surprise than `surprise-ukulele`.", take: "surprise-staccato" },
    { id: "surprise-staccato-2", role: "cue", file: "/audio/cues/surprise-staccato-2.opus", seconds: 3, mood: ["surprised","playful","sparse"], description: "Folk miniature, playful staccato, dry room tone. A barer surprise than `surprise-ukulele`.", take: "surprise-staccato" },
    { id: "surprise-ukulele-1", role: "cue", file: "/audio/cues/surprise-ukulele-1.opus", seconds: 3, mood: ["surprised","whimsical","delicate"], description: "Whimsical folk miniature: plucked ukulele, gentle triangle, sparse toy piano. Pairs with the `surprised` skill.", take: "surprise-ukulele" },
    { id: "surprise-ukulele-2", role: "cue", file: "/audio/cues/surprise-ukulele-2.opus", seconds: 3, mood: ["surprised","whimsical","delicate"], description: "Whimsical folk miniature: plucked ukulele, gentle triangle, sparse toy piano. Pairs with the `surprised` skill.", take: "surprise-ukulele" },
    { id: "surprise-ukulele-3", role: "cue", file: "/audio/cues/surprise-ukulele-3.opus", seconds: 3, mood: ["surprised","whimsical","delicate"], description: "Whimsical folk miniature: plucked ukulele, gentle triangle, sparse toy piano. Pairs with the `surprised` skill.", take: "surprise-ukulele" },
    { id: "suspense-crescendo-1", role: "cue", file: "/audio/cues/suspense-crescendo-1.opus", seconds: 5, mood: ["tense","building","sparse"], description: "Brushed snare and low piano drone, sparse, slow crescendo. Builds into a surprise or a reveal.", take: "suspense-crescendo" },
    { id: "suspense-crescendo-2", role: "cue", file: "/audio/cues/suspense-crescendo-2.opus", seconds: 5, mood: ["tense","building","sparse"], description: "Brushed snare and low piano drone, sparse, slow crescendo. Builds into a surprise or a reveal.", take: "suspense-crescendo" },
    { id: "suspense-crescendo-3", role: "cue", file: "/audio/cues/suspense-crescendo-3.opus", seconds: 5, mood: ["tense","building","sparse"], description: "Brushed snare and low piano drone, sparse, slow crescendo. Builds into a surprise or a reveal.", take: "suspense-crescendo" },
    { id: "suspense-stalking-1", role: "cue", file: "/audio/cues/suspense-stalking-1.opus", seconds: 5, mood: ["tense","intimate","creeping"], description: "Stalking pizzicato strings, brushed snare, low piano drone, dry stage acoustics. Under a sneak or a walk.", take: "suspense-stalking" },
    { id: "suspense-stalking-2", role: "cue", file: "/audio/cues/suspense-stalking-2.opus", seconds: 5, mood: ["tense","intimate","creeping"], description: "Stalking pizzicato strings, brushed snare, low piano drone, dry stage acoustics. Under a sneak or a walk.", take: "suspense-stalking" },
    { id: "suspense-stalking-3", role: "cue", file: "/audio/cues/suspense-stalking-3.opus", seconds: 5, mood: ["tense","intimate","creeping"], description: "Stalking pizzicato strings, brushed snare, low piano drone, dry stage acoustics. Under a sneak or a walk.", take: "suspense-stalking" },
    { id: "suspense-stalking-4", role: "cue", file: "/audio/cues/suspense-stalking-4.opus", seconds: 5, mood: ["tense","intimate","creeping"], description: "Stalking pizzicato strings, brushed snare, low piano drone, dry stage acoustics. Under a sneak or a walk.", take: "suspense-stalking" },
    { id: "laugh-cute", role: "sfx", file: "/audio/sfx/laugh-cute.opus", seconds: 2, mood: ["cute","bright","playful"], description: "Short bright giggle, close mic, dry interior. Pairs with the `laugh` skill." },
];
