/**
 * Curved edge masks for stage layers.
 *
 * A layer that ends in a straight cut reads as a picture that was trimmed. A
 * few big soft curves taking bites out of the edge read as a piece of paper.
 * A mask rather than something drawn into the art, so it applies to every
 * layer already generated and every one generated later.
 *
 * SVG rather than a PNG mask: it scales to any stage size without resampling,
 * costs two kilobytes, and each edge can be curved or left straight
 * independently — which matters, because a band must stay flush along the
 * bottom or it floats off the floor.
 */
import { writeFileSync } from "node:fs";

const W = 1000, H = 500;

// Deterministic, so a rebuild does not silently reshape every stage.
let seed = 20260903;
const rnd = () => (seed = (seed * 1664525 + 1013904223) % 4294967296) / 4294967296;

/**
 * One edge as a run of big smooth curves, always biting INWARDS.
 *
 * Inward only, on purpose. A mask is clipped to the element, so a bulge past
 * the edge does nothing at all — only the bites are visible. Biasing every
 * deviation inward means the whole amplitude is spent on something that shows.
 *
 * Cubic segments rather than many short lines: the ask is big and curvy, and a
 * polyline fine enough to look curved is a hundred points of path data.
 */
function curvedEdge(from, to, depth, waves) {
    const dx = to[0] - from[0], dy = to[1] - from[1];
    const len = Math.hypot(dx, dy);
    const ux = dx / len, uy = dy / len;      // along the edge
    // Inward normal for a clockwise box: rotate the direction a quarter turn.
    // Top edge runs +x, so inward is +y; right edge runs +y, so inward is -x.
    const nx = -uy, ny = ux;

    // Where the curve sits at each wave boundary, and how deep the belly goes.
    const at = (t, inset) => [
        from[0] + ux * len * t + nx * inset,
        from[1] + uy * len * t + ny * inset,
    ];

    let d = "";
    for (let i = 0; i < waves; i++) {
        const t0 = i / waves, t1 = (i + 1) / waves;
        // Each wave gets its own depth, so the edge is not a tidy scallop.
        const belly = depth * (0.35 + rnd() * 0.65);
        const start = depth * rnd() * 0.25;
        const end = depth * rnd() * 0.25;
        const p1 = at(t0 + (t1 - t0) * 0.25, belly);
        const p2 = at(t0 + (t1 - t0) * 0.75, belly);
        const p3 = at(t1, end);
        if (i === 0) d += `L${at(t0, start).map(n => n.toFixed(1)).join(",")}`;
        d += `C${p1.map(n => n.toFixed(1)).join(",")} ${p2.map(n => n.toFixed(1)).join(",")} ${p3.map(n => n.toFixed(1)).join(",")}`;
    }
    return d;
}

/** A closed path round the box, curving only the edges asked for. */
function shape({ top, right, bottom, left }, depth) {
    const c = { tl: [0, 0], tr: [W, 0], br: [W, H], bl: [0, H] };
    const side = (a, b, on, waves) =>
        on ? curvedEdge(a, b, depth, waves) : `L${b[0]},${b[1]}`;
    return [
        `M${c.tl[0]},${c.tl[1]}`,
        side(c.tl, c.tr, top, 4),
        side(c.tr, c.br, right, 2),
        side(c.br, c.bl, bottom, 4),
        side(c.bl, c.tl, left, 2),
        "Z",
    ].join("");
}

const shapes = {
    // A backdrop: every edge, since the camera can pull back from any of them.
    all: shape({ top: true, right: true, bottom: true, left: true }, 26),
    // A band stands on the floor: curve the sides and the top, never the base.
    band: shape({ top: true, right: true, bottom: false, left: true }, 26),
    // Ends only, for a wide layer the camera pans along.
    sides: shape({ top: false, right: true, bottom: false, left: true }, 30),
};

const svg = (d) =>
    `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 ${W} ${H}' preserveAspectRatio='none'>` +
    `<path d='${d}' fill='%23fff'/></svg>`;

const rule = (name, d) => [
    `.torn-${name} {`,
    `    -webkit-mask-image: url("data:image/svg+xml,${svg(d)}");`,
    `    mask-image: url("data:image/svg+xml,${svg(d)}");`,
    `    -webkit-mask-size: 100% 100%;`,
    `    mask-size: 100% 100%;`,
    `    -webkit-mask-repeat: no-repeat;`,
    `    mask-repeat: no-repeat;`,
    `}`,
].join("\n");

writeFileSync("static/troupe/edges.css", `/*
 * Curved edges for stage layers. GENERATED by tools/edges.mjs — do not edit.
 *
 * A straight cut reads as a trimmed picture; a few big soft curves read as a
 * piece of paper. Masks rather than artwork, so they apply to every layer
 * already made as well as every one made later.
 *
 *   .torn-all    every edge — a backdrop, which the camera can pull back from
 *   .torn-band   sides and top, base left flush — a midground or foreground
 *                band, which stands on the floor and must not float
 *   .torn-sides  ends only — a wide layer the camera pans along
 *
 * Every curve bites INWARDS. A mask is clipped to its element, so a bulge past
 * the edge would be invisible; spending the whole amplitude inward is the only
 * way it shows. It also means these crop a little of the art — around 5% at
 * the deepest point — which is why the generator prompt now asks for the outer
 * fifth of a backdrop to be empty.
 *
 * The mask stretches with the element (preserveAspectRatio="none"), so a wide
 * layer gets broader, flatter curves. That is wanted: the curve should read the
 * same size on screen whatever the layer's pixel dimensions.
 */
${rule("all", shapes.all)}

${rule("band", shapes.band)}

${rule("sides", shapes.sides)}
`, "utf8");

console.log("wrote static/troupe/edges.css and three demo svgs");

console.log("wrote static/troupe/edges.css");
