/**
 * Turn the audio manifest into a module the app can import.
 *
 * `static/` is outside the TypeScript project, so rather than teach the build
 * about it this writes a plain module beside the code. Adding a track is an
 * edit to the manifest and a run of this — never a code change.
 *
 *     node tools/sounds.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";

const manifest = JSON.parse(readFileSync("static/audio/manifest.json", "utf8").replace(/^\uFEFF/, ""));
/**
 * `hidden` keeps a sound in the manifest and on disk but out of the app.
 *
 * A track being replaced is not the same as a track being wrong: the file, the
 * mood and the description are worth keeping while the new one is on trial, and
 * losing them to make room is the kind of edit nobody can undo a week later.
 */
const entries = Object.entries(manifest.sounds)
    .filter(([, sound]) => !sound.hidden)
    .map(([id, sound]) => ({ id, ...sound }));
entries.sort((a, b) => a.role.localeCompare(b.role) || a.id.localeCompare(b.id));

const line = (s) => {
    const parts = [
        `id: ${JSON.stringify(s.id)}`,
        `role: ${JSON.stringify(s.role)}`,
        `file: ${JSON.stringify(s.file)}`,
        `seconds: ${Math.round(s.seconds * 10) / 10}`,
        `mood: ${JSON.stringify(s.mood ?? [])}`,
        `description: ${JSON.stringify(s.description ?? "")}`,
        ...(s.take ? [`take: ${JSON.stringify(s.take)}`] : []),
    ];
    return `    { ${parts.join(", ")} },`;
};

writeFileSync("src/lib/collage/sounds.ts", `/**
 * Every sound that ships with the app.
 *
 * GENERATED by tools/sounds.mjs from static/audio/manifest.json — do not edit.
 * Adding a track is an edit to that manifest and a run of the script; nothing
 * here is a decision anybody should be making by hand.
 */

export type SoundRole =
    /** Plays under a whole scene, looping and cross-fading into the next. */
    | "bed"
    /** A short musical sting, fired on a beat. */
    | "cue"
    /** A one-off effect. */
    | "sfx"
    /** Punctuation between the show's parts: curtains, drumrolls, reveals. */
    | "seam";

export interface Sound {
    id: string;
    role: SoundRole;
    /** Served from static/, so this is the URL as the page sees it. */
    file: string;
    seconds: number;
    mood: string[];
    description: string;
    /** Alternate takes of the same prompt share a take name. */
    take?: string;
}

export const SOUNDS: Sound[] = [
${entries.map(line).join("\n")}
];
`, "utf8");

console.log(`wrote src/lib/collage/sounds.ts — ${entries.length} sounds`);
