/**
 * Turn the troupe packs into a module the app can import.
 *
 * Same shape as sounds.mjs, for the same reason: `static/` is outside the
 * TypeScript project, so rather than teach the build about it this writes a
 * plain module beside the code. Adding a pack is a folder, a manifest and a
 * run of this — never a code change.
 *
 *     node tools/troupe.mjs
 *
 * Two kinds of thing are picked up under static/troupe/:
 *  - `<pack>/manifest.json` beside precut webp pieces — the good path, on
 *    stage in seconds;
 *  - loose `<name>.<cols>x<rows>.webp` sheets that still need cutting — the
 *    grid read from the filename, listed so an agent knows to piece_sheet them.
 */
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = "static/troupe";
// midground and foreground are full-width slices of ONE scene, made to stack
// on a backdrop — a parallax kit, not scenery. The first pack to arrive used
// exactly these words and the validator forced them into "backdrop", which
// was the validator being wrong.
const KINDS = new Set(["backdrop", "midground", "foreground", "scenery", "actor"]);

const pieces = [];
const sheets = [];
const packs = [];

if (existsSync(ROOT)) {
    for (const entry of readdirSync(ROOT)) {
        const path = join(ROOT, entry);

        // A loose sheet, its grid in its name: woodland-props.5x5.webp
        const sheet = /^(.+)\.(\d+)x(\d+)\.webp$/i.exec(entry);
        if (sheet && statSync(path).isFile()) {
            sheets.push({
                id: sheet[1],
                file: `/troupe/${entry}`,
                columns: Number(sheet[2]),
                rows: Number(sheet[3]),
            });
            continue;
        }

        if (!statSync(path).isDirectory()) continue;
        const manifestPath = join(path, "manifest.json");
        if (!existsSync(manifestPath)) continue;

        const manifest = JSON.parse(readFileSync(manifestPath, "utf8").replace(/^﻿/, ""));
        packs.push({
            id: entry,
            description: manifest.description ?? "",
            // The image-generation prompt this pack was made with, if whoever
            // made it wrote it down. It is the only way an agent can generate
            // NEW pieces that match: the style is in the prompt, not in
            // anything the pixels can tell it.
            ...(manifest.stylePrompt ? { stylePrompt: manifest.stylePrompt } : {}),
        });
        for (const [id, piece] of Object.entries(manifest.pieces ?? {})) {
            if (!KINDS.has(piece.kind)) {
                // Loudly, at generation time — a typo'd kind that was silently
                // dropped would look like a missing piece three tools later.
                throw new Error(
                    `${entry}/${id}: kind ${JSON.stringify(piece.kind)} is not one of ` +
                    `backdrop | midground | foreground | scenery | actor`);
            }
            const file = join(path, piece.file);
            if (!existsSync(file)) throw new Error(`${entry}/${id}: ${piece.file} does not exist`);
            pieces.push({
                id: `${entry}/${id}`,
                pack: entry,
                kind: piece.kind,
                file: `/troupe/${entry}/${piece.file}`,
                mood: piece.mood ?? [],
                description: piece.description ?? "",
                ...(piece.take ? { take: `${entry}/${piece.take}` } : {}),
            });
        }
    }
}

pieces.sort((a, b) => a.pack.localeCompare(b.pack) || a.kind.localeCompare(b.kind) || a.id.localeCompare(b.id));
packs.sort((a, b) => a.id.localeCompare(b.id));
sheets.sort((a, b) => a.id.localeCompare(b.id));

const pieceLine = (p) => {
    const parts = [
        `id: ${JSON.stringify(p.id)}`,
        `pack: ${JSON.stringify(p.pack)}`,
        `kind: ${JSON.stringify(p.kind)}`,
        `file: ${JSON.stringify(p.file)}`,
        `mood: ${JSON.stringify(p.mood)}`,
        `description: ${JSON.stringify(p.description)}`,
        ...(p.take ? [`take: ${JSON.stringify(p.take)}`] : []),
    ];
    return `    { ${parts.join(", ")} },`;
};

const sheetLine = (s) =>
    `    { id: ${JSON.stringify(s.id)}, file: ${JSON.stringify(s.file)}, ` +
    `columns: ${s.columns}, rows: ${s.rows} },`;

writeFileSync("src/lib/collage/troupe.ts", `/**
 * The troupe: ready-made art that ships with the theatre.
 *
 * GENERATED by tools/troupe.mjs from static/troupe/ — do not edit. Adding a
 * pack is a folder, a manifest and a run of that script; see
 * static/troupe/README.md for the conventions.
 */

export type TroupeKind = "backdrop" | "midground" | "foreground" | "scenery" | "actor";

export interface TroupePiece {
    /** "<pack>/<name>" — what an agent asks for. */
    id: string;
    pack: string;
    kind: TroupeKind;
    /** Served from static/, so this is the URL as the page sees it. */
    file: string;
    mood: string[];
    description: string;
    /** Pieces sharing a take are the same character in another pose. */
    take?: string;
}

/** An uncut sheet, its grid read from its filename. Needs piece_sheet. */
export interface TroupeSheet {
    id: string;
    file: string;
    columns: number;
    rows: number;
}

/** A pack: its blurb, and — when recorded — the prompt that generated it. */
export interface TroupePack {
    id: string;
    description: string;
    stylePrompt?: string;
}

export const TROUPE_PACKS: TroupePack[] = [
${packs.map(pack => {
    const parts = [
        `id: ${JSON.stringify(pack.id)}`,
        `description: ${JSON.stringify(pack.description)}`,
        ...(pack.stylePrompt ? [`stylePrompt: ${JSON.stringify(pack.stylePrompt)}`] : []),
    ];
    return `    { ${parts.join(", ")} },`;
}).join("\n") || "    // No packs installed."}
];

export const TROUPE: TroupePiece[] = [
${pieces.map(pieceLine).join("\n") || "    // No packs installed. static/troupe/README.md says how to add one."}
];

export const TROUPE_SHEETS: TroupeSheet[] = [
${sheets.map(sheetLine).join("\n") || "    // No uncut sheets."}
];
`);

console.log(`troupe: ${pieces.length} piece(s) in ${new Set(pieces.map(p => p.pack)).size} pack(s), ${sheets.length} sheet(s)`);
